project:
  type: website

website:
  title: "statCTR"
  site-url: https://www.statCTR.com
  google-analytics: "G-FL4BZV7N6M"
  navbar:
    left:
      - href: videos.qmd
        text: Video Repository
      - href: resources.qmd
        text: Resource Repository
      - about.qmd
  page-footer: 
    left: |
      © 2025 ASA Consulting Section  
      A community of the American Statistical Association  
    right: |
      <small>
      The content on this site reflects the views of individual contributors and does not represent official positions of the ASA.  
      <a href="/about.html#disclaimer">Learn more</a>
      </small>
  repo-url: https://github.com/petersonR/statCTR
  repo-actions: [issue]
  cookie-consent: true 
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute: 
  freeze: auto